version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome:129.0
    ports:
      - "4444:4444"
      - "7900:7900"  # VNC viewer (http://localhost:7900)
    shm_size: 2gb

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    environment:
      - SELENIUM_URL=http://selenium:4444/wd/hub
    depends_on:
      - selenium
    entrypoint: ["tail", "-f", "/dev/null"]  # 開発用に常駐